STO_SERVER_LIB_DIR = $(CONTROL_ROOT_DIR)/server/
STO_SERVER_HEADER_DIR = $(CONTROL_ROOT_DIR)/server/include

STO_SERVER_CFLAGS = -I$(STO_SERVER_HEADER_DIR)
STO_SERVER_LDFLAGS = -L$(STO_SERVER_LIB_DIR)

STO_SERVER_LIB := -lsto_server
